/* يومي 3.0 — تحسينات المشاريع، عبادتي، التقويم، الرفع والتخصيص */
(() => {
  const state={client:null,project:null,course:null};
  const bucket='yomi-memories', urls=new Set();
  function ensure(){
    data.fastingLog??=[]; data.fastingPrefs??={mondayThursday:true,whiteDays:true,arafah:true,ashura:true};
    data.debtPeople??=[]; data.clients??=[]; data.learningSpaces??=[];
    data.designSettings??={background:null,stickers:[]}; data.designSettings.stickers??=[];
    data.cyclePeriodLength??=7;
    for(const c of data.clients){c.projects??=[];for(const p of c.projects){
      p.projectType??='مشروع';p.assets??=[];p.payments??=[];p.checklist??=[];p.publishDelay??=1;
      if(!p.payments.length&&Number(p.paid||0)>0&&!p._paidMigrated){p.payments.push({id:id(),amount:Number(p.paid),date:p.due||today(),note:'دفعة سابقة'});p._paidMigrated=true}
      if(!p.checklist.length&&p.required){p.checklist=String(p.required).split(/\n+/).map(x=>x.trim()).filter(Boolean).map(text=>({id:id(),text,done:false}));p.required=''}
    }}
  }
  const cash=n=>Number(n||0).toLocaleString('en-US')+' ₪';
  const projectPaid=p=>sum((p.payments||[]).map(x=>Number(x.amount)||0));
  const publishDate=p=>p.publishDate||(p.eventDate?dayAfter(p.eventDate,Number(p.publishDelay??1)):'');
  const monthKey=d=>d.slice(0,7);
  function monthOffset(d,n){const x=new Date(d.slice(0,7)+'-01T12:00:00Z');x.setUTCMonth(x.getUTCMonth()+n);return x.toISOString().slice(0,10)}
  function clientItems(month){
    const out=[];for(const c of data.clients)for(const p of c.projects||[]){
      if(p.due?.startsWith(month))out.push({kind:'client',cid:c.id,pid:p.id,date:p.due,title:'تسليم · '+p.title,icon:'📦',color:'#bb925c'});
      if(p.eventDate?.startsWith(month))out.push({kind:'client',cid:c.id,pid:p.id,date:p.eventDate,title:'المناسبة · '+p.title,icon:'💍',color:'#a8738b'});
      const pd=publishDate(p);if(pd?.startsWith(month)&&!p.published)out.push({kind:'client',cid:c.id,pid:p.id,date:pd,title:'انشري المشروع · '+p.title,icon:'📱',color:'#749485'});
    }return out
  }
  function plannerRows(month){
    const a=[];for(const x of data.tasks||[])if(x.date?.startsWith(month))a.push({kind:'task',date:x.date,title:x.title,icon:'✓',color:'#7f96ad'});
    for(const x of data.calendarEvents||[])if(x.date?.startsWith(month))a.push({kind:'event',date:x.date,title:x.title,icon:x.sticker||'•',color:x.color||'#7f96ad',time:x.time||''});
    for(const x of data.projects||[])if(x.due?.startsWith(month))a.push({kind:'project',date:x.due,title:x.title,icon:'💼',color:'#bb925c',time:x.time||''});
    a.push(...clientItems(month));return a.sort((x,y)=>(x.date+(x.time||'')).localeCompare(y.date+(y.time||'')))
  }
  function planner(){
    const month=monthKey(selected),first=month+'-01',days=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate(),pad=(new Date(first+'T12:00:00Z').getUTCDay()+6)%7,rows=plannerRows(month),cells=[];
    for(let i=0;i<pad;i++)cells.push('<div class="cal-cell cal-empty"></div>');
    for(let n=1;n<=days;n++){const d=month+'-'+String(n).padStart(2,'0'),r=rows.filter(x=>x.date===d);cells.push('<button class="cal-cell '+(d===today()?'today ':'')+(d===selected?'selected':'')+'" data-v3-day="'+d+'"><b>'+n+'</b><span class="cal-dots">'+r.slice(0,4).map(x=>'<i style="background:'+x.color+'"></i>').join('')+'</span><small>'+((r.length?String(r.length)+' عنصر':''))+'</small></button>')}
    const r=rows.filter(x=>x.date===selected);
    return '<div class="panel glass-panel"><div class="row between"><div><h2>Calendar Planner</h2><p class="sub">اضغطي على التاريخ ليظهر كل ما عندك فيه.</p></div><div class="row"><button class="soft" data-v3-month="-1">‹</button><strong>'+dateLabel(first)+'</strong><button class="soft" data-v3-month="1">›</button></div></div><div class="calendar-week"><span>الإثنين</span><span>الثلاثاء</span><span>الأربعاء</span><span>الخميس</span><span>الجمعة</span><span>السبت</span><span>الأحد</span></div><div class="calendar-grid">'+cells.join('')+'</div></div>'+
    '<div class="panel"><h3>'+dateLabel(selected)+'</h3>'+(r.map(x=>'<div class="item"><span class="event-chip" style="--chip:'+x.color+'">'+x.icon+'</span><div class="grow"><b>'+safe(x.title)+'</b><small>'+(x.time?safe(x.time)+' · ':'')+(x.kind==='client'?'مشروع عميل':x.kind==='task'?'مهمة':x.kind==='project'?'مشروع':'موعد')+'</small></div>'+(x.kind==='client'?'<button data-v3-open="'+x.cid+':'+x.pid+'">فتح المشروع</button>':'')+'</div>').join('')||'<div class="empty">ما في شيء مسجّل لهذا اليوم</div>')+'</div>'+
    '<div class="panel"><h3>إضافة موعد</h3><form id="v3Event" class="row"><label class="field">الاسم<input name="title" required></label><label class="field">التاريخ<input name="date" type="date" value="'+selected+'" required></label><label class="field">الوقت<input name="time" type="time"></label><label class="field">اللون<select name="color"><option value="#7f96ad">أزرق</option><option value="#749485">أخضر</option><option value="#bb925c">ذهبي</option><option value="#a8738b">وردي</option></select></label><button class="primary">إضافة</button></form></div>'
  }
  function fastTips(){
    const d=new Date(selected+'T12:00:00Z'),w=d.getUTCDay(),t=[];
    if(data.fastingPrefs.mondayThursday&&(w===1||w===4))t.push(w===1?'الاثنين':'الخميس');
    try{const p=new Intl.DateTimeFormat('en-u-ca-islamic',{day:'numeric',month:'numeric',timeZone:TZ}).formatToParts(d),hd=Number(p.find(x=>x.type==='day')?.value),hm=Number(p.find(x=>x.type==='month')?.value);if(data.fastingPrefs.whiteDays&&[13,14,15].includes(hd))t.push('الأيام البيض');if(data.fastingPrefs.ashura&&hm===1&&hd===10)t.push('عاشوراء');if(data.fastingPrefs.arafah&&hm===12&&hd===9)t.push('عرفة')}catch{}return t
  }
  function worship(){
    const prayers=['الفجر','الظهر','العصر','المغرب','العشاء'],p=data.prayerChecks?.[selected]||{},fast=data.fastingLog.find(x=>x.date===selected),tips=fastTips(),dh=(data.dhikrs||[]).filter(x=>activeDhikr(x,selected));
    return '<div class="panel"><h2>عبادتي</h2><p class="sub">أذكار «يومي» و«عبادتي» من نفس السجل.</p>'+datePicker()+'<div class="prayer-grid">'+prayers.map(n=>'<label class="prayer-card"><input type="checkbox" data-v3-prayer="'+n+'" '+(p[n]?'checked':'')+'><span>🕌 '+n+'</span></label>').join('')+'</div><p class="sub">المسجّل اليوم: '+prayers.filter(n=>p[n]).length+' من 5.</p></div>'+
    '<div class="panel"><div class="row between"><h3>الصيام</h3>'+(tips.length?'<span class="fast-tip">🌙 تذكير: '+safe(tips.join(' · '))+'</span>':'')+'</div><form id="v3Fast" class="row"><label class="field">نوع الصيام<select name="type">'+['قضاء رمضان','نفل','نذر','كفارة','لوجه الله تعالى'].map(v=>'<option '+(fast?.type===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="field">التاريخ<input name="date" type="date" value="'+selected+'"></label><label class="field">ملاحظة<input name="note" value="'+safe(fast?.note||'')+'"></label><button class="primary">'+(fast?'تحديث':'تسجيل')+'</button></form>'+(fast?'<div class="notice">مسجّل: '+safe(fast.type)+' <button class="soft" data-v3-fast-del="'+fast.id+'">حذف</button></div>':'')+'<details><summary>تذكيرات صيام النفل</summary><div class="fasting-prefs"><label><input type="checkbox" data-v3-pref="mondayThursday" '+(data.fastingPrefs.mondayThursday?'checked':'')+'> الاثنين والخميس</label><label><input type="checkbox" data-v3-pref="whiteDays" '+(data.fastingPrefs.whiteDays?'checked':'')+'> الأيام البيض</label><label><input type="checkbox" data-v3-pref="arafah" '+(data.fastingPrefs.arafah?'checked':'')+'> عرفة</label><label><input type="checkbox" data-v3-pref="ashura" '+(data.fastingPrefs.ashura?'checked':'')+'> عاشوراء</label></div></details></div>'+
    '<div class="panel"><h3>أذكاري</h3>'+(dh.map(x=>'<div class="item"><div class="grow"><b>'+safe(x.title)+'</b><small>'+dhikrCount(x,selected)+' / '+dhikrTargetOn(x,selected)+'</small></div><button data-v3-dhikr="'+x.id+'">+1</button><button data-v3-dhikr-many="'+x.id+'">إضافة عدد</button></div>').join('')||'<div class="empty">أضيفي الأذكار من صفحة مهامي.</div>')+'</div>'
  }
  function clients(){
    if(!data.clients.length||!state.client||!data.clients.some(x=>x.id===state.client))return '<div class="panel"><h2>العملاء والمشاريع</h2><form id="v3Client" class="row"><label class="field">اسم العميل<input name="name" required></label><button class="primary">إنشاء ملف</button></form><div class="client-grid">'+(data.clients.map(c=>'<button class="client-card" data-v3-client="'+c.id+'"><b>'+safe(c.name)+'</b><small>'+(c.projects||[]).length+' مشروع</small></button>').join('')||'<div class="empty">ما في عملاء بعد</div>')+'</div></div>';
    const c=data.clients.find(x=>x.id===state.client);c.projects??=[];
    if(!state.project||!c.projects.some(x=>x.id===state.project))return '<div class="panel"><button class="soft" data-v3-client-back>‹ كل العملاء</button><h2>'+safe(c.name)+'</h2><form id="v3ProjectNew"><div class="row"><label class="field">اسم المشروع<input name="title" required></label><label class="field">النوع<select name="type"><option>كرت دعوة</option><option>تصميم عرس</option><option>إعلان</option><option>تصميم آخر</option></select></label></div><div class="row"><label class="field">موعد التسليم<input name="due" type="date"></label><label class="field">موعد العرس/المناسبة<input name="event" type="date"></label><label class="field">النشر بعد المناسبة<select name="delay"><option value="1">بعد يوم</option><option value="2">بعد يومين</option><option value="3">بعد 3 أيام</option></select></label></div><div class="row"><label class="field">المبلغ المتفق ₪<input name="amount" type="number" min="0" step=".01"></label><label class="field">دفعة أولى ₪<input name="first" type="number" min="0" step=".01"></label></div><button class="primary">إضافة مشروع</button></form>'+(c.projects.map(p=>'<button class="project-card" data-v3-project="'+p.id+'"><div><b>'+safe(p.title)+'</b><small>'+safe(p.projectType||'مشروع')+' · '+(p.due?'التسليم '+dateLabel(p.due):'بدون موعد')+'</small></div><span>'+cash(Math.max(0,Number(p.amount||0)-projectPaid(p)))+' باقي</span></button>').join('')||'<div class="empty">أضيفي أول مشروع</div>')+'</div>';
    const p=c.projects.find(x=>x.id===state.project),paid=projectPaid(p),remain=Math.max(0,Number(p.amount||0)-paid),pub=publishDate(p);
    return '<div class="panel"><button class="soft" data-v3-project-back>‹ '+safe(c.name)+'</button><div class="row between"><div><h2>'+safe(p.title)+'</h2><span class="project-type">'+safe(p.projectType||'مشروع')+'</span></div><button class="'+(p.published?'primary':'soft')+'" data-v3-published="'+p.id+'">'+(p.published?'✓ تم النشر':'تحديد تم النشر')+'</button></div><div class="grid"><div class="stat">الحالة<b class="stat-small">'+safe(p.status||'جديد')+'</b></div><div class="stat">التسليم<b class="stat-small">'+(p.due?dateLabel(p.due):'—')+'</b></div><div class="stat">المناسبة<b class="stat-small">'+(p.eventDate?dateLabel(p.eventDate):'—')+'</b></div><div class="stat">المتفق<b>'+cash(p.amount)+'</b></div><div class="stat">المستلم<b>'+cash(paid)+'</b></div><div class="stat">المتبقي<b>'+cash(remain)+'</b></div></div>'+(pub?'<div class="notice">📱 موعد النشر: '+dateLabel(pub)+(p.published?' · ✓ تم':' · انشري المشروع وجهزي صور/Reel')+'</div>':'')+'<form id="v3ProjectEdit"><div class="row"><label class="field">الحالة<select name="status">'+['جديد','جاري','بانتظار العميل','تعديل','جاهز','تم التسليم','مغلق'].map(v=>'<option '+(p.status===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="field">النوع<select name="type">'+['كرت دعوة','تصميم عرس','إعلان','تصميم آخر'].map(v=>'<option '+(p.projectType===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="field">التسليم<input name="due" type="date" value="'+safe(p.due||'')+'"></label></div><div class="row"><label class="field">المناسبة<input name="event" type="date" value="'+safe(p.eventDate||'')+'"></label><label class="field">النشر بعد كم يوم<input name="delay" type="number" min="0" max="30" value="'+Number(p.publishDelay??1)+'"></label><label class="field">موعد نشر مخصص<input name="publish" type="date" value="'+safe(p.publishDate||'')+'"></label></div><label class="field">ملاحظات<textarea name="notes">'+safe(p.notes||'')+'</textarea></label><button class="primary">حفظ</button></form></div>'+
    '<div class="panel"><h3>المطلوب والتنفيذ</h3><form id="v3CheckNew" class="row"><label class="field">بند جديد<input name="text" required></label><button class="soft">إضافة</button></form>'+(p.checklist.map(i=>'<label class="check-row"><input type="checkbox" data-v3-check="'+i.id+'" '+(i.done?'checked':'')+'><span class="'+(i.done?'done':'')+'">'+safe(i.text)+'</span><button type="button" data-v3-check-del="'+i.id+'">×</button></label>').join('')||'<div class="empty">أضيفي المطلوب كبنود.</div>')+'</div>'+
    '<div class="panel"><h3>الدفعات</h3><form id="v3Pay" class="row"><label class="field">المبلغ<input name="amount" type="number" min=".01" step=".01" required></label><label class="field">التاريخ<input name="date" type="date" value="'+selected+'"></label><label class="field">ملاحظة<input name="note"></label><button class="soft">إضافة دفعة</button></form>'+(p.payments.map(x=>'<div class="item"><div class="grow"><b>'+cash(x.amount)+'</b><small>'+safe(x.date)+' · '+safe(x.note||'')+'</small></div><button data-v3-pay-del="'+x.id+'">حذف</button></div>').join('')||'<div class="empty">ما في دفعات.</div>')+'</div>'+
    '<div class="panel"><h3>الصور والاعتمادات</h3><form id="v3Assets"><div class="row"><label class="field">الصور<input name="file" type="file" accept="image/png,image/jpeg,image/webp" multiple required></label><label class="field">الحالة<select name="status"><option>مرجع</option><option>قيد العمل</option><option>معتمدة</option><option>غير معتمدة</option><option>تحتاج تعديل</option><option>نهائية</option></select></label><label class="field">ملاحظة<input name="caption"></label></div><div class="upload-preview" data-v3-preview></div><p class="sub" data-v3-status></p><button class="soft">إضافة الصور</button></form><div class="asset-grid">'+(p.assets.map(a=>'<div class="asset-card"><div class="media-box" data-v3-media="'+safe(a.local||a.path||'')+'"></div><b>'+safe(a.status)+'</b><small>'+safe(a.caption||'')+'</small><button data-v3-asset-del="'+a.id+'">حذف</button></div>').join('')||'<div class="empty">ما في صور.</div>')+'</div></div>'
  }
  function learning(){
    if(!state.course||!data.learningSpaces.some(x=>x.id===state.course))return '<div class="panel"><h2>دفتر تعلّمي</h2><form id="v3Course" class="row"><label class="field">اسم الدورة<input name="title" required></label><button class="primary">إضافة دورة</button></form><div class="client-grid">'+(data.learningSpaces.map(c=>'<button class="client-card" data-v3-course="'+c.id+'"><b>'+safe(c.title)+'</b><small>'+(c.items||[]).length+' مادة</small></button>').join('')||'<div class="empty">أضيفي دورة.</div>')+'</div></div>';
    const c=data.learningSpaces.find(x=>x.id===state.course);c.items??=[];
    return '<div class="panel"><button class="soft" data-v3-course-back>‹ كل الدورات</button><h2>'+safe(c.title)+'</h2><form id="v3CourseItem"><div class="row"><label class="field">العنوان<input name="title" required></label><label class="field">النوع<select name="type"><option value="note">ملاحظة</option><option value="video">فيديو/رابط</option><option value="image">صورة نوت</option></select></label><label class="field">الرابط<input name="url" type="url"></label><label class="field">الصورة<input name="file" type="file" accept="image/png,image/jpeg,image/webp"></label></div><label class="field">ملاحظاتي<textarea name="note"></textarea></label><label><input name="watched" type="checkbox"> تم</label><p class="sub" data-v3-learning-status></p><button class="primary">حفظ</button></form></div><div class="panel">'+(c.items.map(i=>'<div class="learning-item '+(i.watched?'done-card':'')+'">'+(i.media?'<div class="learning-media media-box" data-v3-media="'+safe(i.media.local||i.media.path||'')+'"></div>':i.src?'<img src="'+i.src+'" alt="">':'')+'<div class="grow"><b>'+safe(i.title)+'</b><small>'+safe(i.type)+'</small><p>'+safe(i.note||'')+'</p>'+(i.url?'<a href="'+safe(i.url)+'" target="_blank">فتح الرابط</a>':'')+'</div><button data-v3-course-toggle="'+i.id+'">'+(i.watched?'إرجاع':'تم')+'</button></div>').join('')||'<div class="empty">ما في مواد.</div>')+'</div>'
  }
  function customize(){
    const d=data.designSettings;
    return '<div class="panel"><h2>تصميم يومي</h2><form id="v3Bg"><label class="field">صورة الخلفية<input name="file" type="file" accept="image/png,image/jpeg,image/webp" required></label><div class="upload-preview" data-v3-bg-prev></div><p class="sub" data-v3-bg-status></p><button class="primary">حفظ الخلفية</button><button type="button" class="soft" data-v3-bg-clear>إزالة</button></form></div>'+
    '<div class="panel"><h3>Stickers</h3><form id="v3Sticker"><div class="row"><label class="field">صورة Sticker<input name="file" type="file" accept="image/png,image/webp,image/jpeg"></label><label class="field">أو Emoji<input name="text" maxlength="8"></label><label class="field">الصفحة<select name="target"><option value="all">كل التطبيق</option><option value="lock">صفحة الدخول</option><option value="home">يومي</option><option value="planner">التقويم</option><option value="worship">عبادتي</option><option value="learning">تعلّمي</option><option value="clients">العملاء</option><option value="finance">مالي</option></select></label></div><div class="row"><label class="field">أفقي<input name="x" type="range" min="5" max="95" value="85"></label><label class="field">عمودي<input name="y" type="range" min="5" max="95" value="18"></label><label class="field">الحجم<input name="size" type="range" min="24" max="140" value="54"></label></div><div class="upload-preview" data-v3-sticker-prev></div><button class="soft">إضافة Sticker</button></form>'+(d.stickers.map(s=>'<div class="item"><div class="grow"><div class="sticker-thumb" '+((s.local||s.path)?'data-v3-media="'+safe(s.local||s.path)+'"':'')+'>'+safe(s.text||'')+'</div><small>'+safe(s.target||'all')+' · '+s.size+'px</small></div><button data-v3-sticker-toggle="'+s.id+'">'+(s.hidden?'إظهار':'إخفاء')+'</button><button data-v3-sticker-del="'+s.id+'">حذف</button></div>').join('')||'<div class="empty">ما في Stickers.</div>')+'</div>'
  }
  function homeExtra(){
    const dh=(data.dhikrs||[]).filter(x=>activeDhikr(x,selected)).slice(0,4),work=clientItems(monthKey(selected)).filter(x=>x.date>=selected).slice(0,4);
    return '<div class="panel quick-dhikr"><div class="row between"><h3>أذكاري السريعة</h3><button class="soft" data-go="worship">عبادتي</button></div>'+(dh.map(x=>'<div class="item"><div class="grow"><b>'+safe(x.title)+'</b><small>'+dhikrCount(x,selected)+' / '+dhikrTargetOn(x,selected)+'</small></div><button data-v3-dhikr="'+x.id+'">+1</button><button data-v3-dhikr-many="'+x.id+'">إضافة عدد</button></div>').join('')||'<div class="empty">أضيفي ذكرًا من مهامي.</div>')+'</div><div class="panel"><div class="row between"><h3>مواعيد مشاريع العملاء</h3><button class="soft" data-go="planner">التقويم</button></div>'+(work.map(x=>'<div class="item"><span class="event-chip" style="--chip:'+x.color+'">'+x.icon+'</span><div class="grow"><b>'+safe(x.title)+'</b><small>'+dateLabel(x.date)+'</small></div><button data-v3-open="'+x.cid+':'+x.pid+'">فتح</button></div>').join('')||'<div class="empty">ما في مواعيد قادمة.</div>')+'</div>'
  }
  function cycleExtra(){
    const ps=[...data.periods].sort((a,b)=>b.start.localeCompare(a.start)),open=ps.find(x=>!x.end),len=Number(data.cyclePeriodLength||7);
    return '<div class="panel v3-cycle"><h2>تعديل سجل الدورة</h2><div class="row"><label class="field">المدة المعتادة للأيام<input id="v3CycleLen" type="number" min="1" max="14" value="'+len+'"></label><button class="soft" data-v3-cycle-save>حفظ</button></div>'+(open?'<div class="notice">النهاية المقترحة: '+dateLabel(dayAfter(open.start,len-1))+'</div>':'')+(ps.map(x=>'<div class="item"><div class="grow"><b>'+dateLabel(x.start)+(x.end?' — '+dateLabel(x.end):' · مفتوحة')+'</b></div><button data-v3-period="'+x.id+'">تعديل البداية/النهاية</button></div>').join('')||'<div class="empty">لا يوجد سجل.</div>')+'</div>'
  }
  function debtExtra(){
    return '<div class="panel v3-debts"><h2>حساب الأشخاص</h2><p class="sub">مستقل عن المصاريف والدخل.</p><form id="v3DebtPerson" class="row"><label class="field">الاسم<input name="name" required></label><button class="primary">إضافة شخص</button></form>'+((data.debtPeople||[]).map(p=>{const net=sum((p.transactions||[]).map(t=>Number(t.delta)||0));return '<div class="debt-person"><div class="row between"><b>'+safe(p.name)+'</b><strong>'+(net>0?cash(net)+' لصالحك':net<0?cash(Math.abs(net))+' عليك':'0 ₪')+'</strong></div><form class="row" data-v3-debt="'+p.id+'"><label class="field">الحركة<select name="type"><option value="owed">مبلغ مستحق لي</option><option value="owe">مبلغ مستحق عليّ</option><option value="received">استلام دفعة</option><option value="paid">دفع دفعة</option></select></label><label class="field">المبلغ<input name="amount" type="number" min=".01" step=".01" required></label><label class="field">التاريخ<input name="date" type="date" value="'+selected+'"></label><label class="field">ملاحظة<input name="note"></label><button class="soft">إضافة حركة</button></form></div>'}).join('')||'<div class="empty">أضيفي أول شخص.</div>')+'</div>'
  }

  function db(){return new Promise((ok,no)=>{const r=indexedDB.open('yomi-v3-media-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
  async function put(k,v){const d=await db();try{await new Promise((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put(v,k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}finally{d.close()}}
  async function get(k){const d=await db();try{return await new Promise((ok,no)=>{const t=d.transaction('files','readonly'),r=t.objectStore('files').get(k);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}finally{d.close()}}
  async function del(k){const d=await db();try{await new Promise((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').delete(k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}finally{d.close()}}
  async function imageBlob(file,max=1500,q=.8,alpha=false){if(!file?.size||!/^image\/(png|jpeg|webp)$/i.test(file.type||''))throw Error('type');const b=await createImageBitmap(file),s=Math.min(1,max/Math.max(b.width,b.height)),cv=document.createElement('canvas');cv.width=Math.max(1,Math.round(b.width*s));cv.height=Math.max(1,Math.round(b.height*s));cv.getContext('2d').drawImage(b,0,0,cv.width,cv.height);b.close?.();return await new Promise((ok,no)=>cv.toBlob(x=>x?ok(x):no(Error('compress')),alpha?'image/webp':'image/jpeg',q))}
  async function saveImage(file,opt={}){const b=await imageBlob(file,opt.max||1500,opt.q||.8,!!opt.alpha),local='local:'+id();await put(local,b);return {local,mime:b.type}}
  function records(){const r=[];for(const c of data.clients)for(const p of c.projects||[])for(const a of p.assets||[])if(a.local)r.push(a);for(const c of data.learningSpaces)for(const i of c.items||[])if(i.media?.local)r.push(i.media);if(data.designSettings.backgroundMedia?.local)r.push(data.designSettings.backgroundMedia);for(const s of data.designSettings.stickers||[])if(s.local)r.push(s);return r}
  async function syncMedia(){const s=window.yomiMemoriesSession?.();if(!s||!navigator.onLine)return;for(const r of records()){const old=r.local;try{const b=await get(old);if(!b)continue;const ext=b.type.includes('webp')?'webp':'jpg',path=s.user.id+'/planner-'+id()+'.'+ext,{error}=await s.client.storage.from(bucket).upload(path,b,{contentType:b.type,upsert:false});if(error)throw error;await put(s.user.id+':'+path,b);r.path=path;delete r.local;save();await del(old)}catch(e){console.error(e)}}}
  async function blobFor(ref){let b=await get(ref);const s=window.yomiMemoriesSession?.();if(!b&&s){b=await get(s.user.id+':'+ref);if(!b&&ref.startsWith(s.user.id+'/')&&navigator.onLine){const {data:x,error}=await s.client.storage.from(bucket).download(ref);if(error)throw error;b=x;await put(s.user.id+':'+ref,b)}}return b}
  async function paint(){
    for(const u of urls)URL.revokeObjectURL(u);urls.clear();
    for(const box of document.querySelectorAll('[data-v3-media]'))try{const b=await blobFor(box.dataset.v3Media);if(!b||!box.isConnected)continue;const u=URL.createObjectURL(b);urls.add(u);const im=document.createElement('img');im.src=u;im.alt='';box.replaceChildren(im)}catch{}
    const bg=data.designSettings.backgroundMedia;if(bg)try{const b=await blobFor(bg.local||bg.path);if(b){const u=URL.createObjectURL(b);urls.add(u);document.documentElement.style.setProperty('--yomi-user-bg','url("'+u+'")');document.body.dataset.userBg='1'}}catch{}
    syncMedia()
  }
  function stickers(){
    document.querySelectorAll('.yomi-v3-sticker').forEach(x=>x.remove());
    const lock=!document.getElementById('lock')?.classList.contains('hidden');
    for(const s of data.designSettings.stickers||[]){if(s.hidden)continue;const t=s.target||'all';if(t!=='all'&&t!==page&&!(t==='lock'&&lock))continue;const e=document.createElement('div');e.className='yomi-v3-sticker';e.style.left=s.x+'%';e.style.top=s.y+'%';e.style.width=e.style.height=s.size+'px';e.style.fontSize=s.size+'px';if(s.text)e.textContent=s.text;if(s.local||s.path)e.dataset.v3Media=s.local||s.path;document.body.appendChild(e)}
  }

  function attach(){
    document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()});
    document.querySelectorAll('[data-v3-day]').forEach(b=>b.onclick=()=>{selected=b.dataset.v3Day;render()});
    document.querySelectorAll('[data-v3-month]').forEach(b=>b.onclick=()=>{selected=monthOffset(selected,Number(b.dataset.v3Month));render()});
    document.querySelectorAll('[data-v3-open]').forEach(b=>b.onclick=()=>{const z=b.dataset.v3Open.split(':');state.client=z[0];state.project=z[1];page='clients';render()});
    const ev=$('#v3Event');if(ev)ev.onsubmit=e=>{e.preventDefault();const f=new FormData(ev);data.calendarEvents.push({id:id(),title:f.get('title').trim(),date:f.get('date'),time:f.get('time'),color:f.get('color'),sticker:'•',done:false});selected=f.get('date');save();render()};
    document.querySelectorAll('[data-v3-prayer]').forEach(x=>x.onchange=()=>{data.prayerChecks[selected]??={};data.prayerChecks[selected][x.dataset.v3Prayer]=x.checked;save();render()});
    document.querySelectorAll('[data-v3-dhikr]').forEach(b=>b.onclick=()=>{const x=data.dhikrs.find(z=>z.id===b.dataset.v3Dhikr);x.counts??={};x.counts[selected]=(Number(x.counts[selected])||0)+1;save();render()});
    document.querySelectorAll('[data-v3-dhikr-many]').forEach(b=>b.onclick=()=>{const x=data.dhikrs.find(z=>z.id===b.dataset.v3DhikrMany),v=prompt('كم مرة بدك تضيفي؟','10');if(v===null)return;const n=parseCount(v);if(!Number.isSafeInteger(n)||n<1)return;x.counts??={};x.counts[selected]=(Number(x.counts[selected])||0)+n;save();render()});
    const ff=$('#v3Fast');if(ff)ff.onsubmit=e=>{e.preventDefault();const f=new FormData(ff),d=f.get('date'),o=data.fastingLog.find(x=>x.date===d),r={id:o?.id||id(),date:d,type:f.get('type'),note:f.get('note').trim()};o?Object.assign(o,r):data.fastingLog.push(r);selected=d;save();render()};
    document.querySelectorAll('[data-v3-fast-del]').forEach(b=>b.onclick=()=>{data.fastingLog=data.fastingLog.filter(x=>x.id!==b.dataset.v3FastDel);save();render()});
    document.querySelectorAll('[data-v3-pref]').forEach(x=>x.onchange=()=>{data.fastingPrefs[x.dataset.v3Pref]=x.checked;save();render()});

    const cf=$('#v3Client');if(cf)cf.onsubmit=e=>{e.preventDefault();const f=new FormData(cf),c={id:id(),name:f.get('name').trim(),projects:[]};data.clients.push(c);state.client=c.id;save();render()};
    document.querySelectorAll('[data-v3-client]').forEach(b=>b.onclick=()=>{state.client=b.dataset.v3Client;state.project=null;render()});
    document.querySelector('[data-v3-client-back]')?.addEventListener('click',()=>{state.client=null;state.project=null;render()});
    document.querySelectorAll('[data-v3-project]').forEach(b=>b.onclick=()=>{state.project=b.dataset.v3Project;render()});
    document.querySelector('[data-v3-project-back]')?.addEventListener('click',()=>{state.project=null;render()});
    const pn=$('#v3ProjectNew');if(pn)pn.onsubmit=e=>{e.preventDefault();const c=data.clients.find(x=>x.id===state.client),f=new FormData(pn),event=f.get('event'),delay=Number(f.get('delay')||1),p={id:id(),title:f.get('title').trim(),projectType:f.get('type'),due:f.get('due'),eventDate:event,publishDelay:delay,publishDate:event?dayAfter(event,delay):'',published:false,amount:Number(f.get('amount')||0),status:'جديد',assets:[],payments:[],checklist:[],notes:''},first=Number(f.get('first')||0);if(first>0)p.payments.push({id:id(),amount:first,date:selected,note:'دفعة أولى'});c.projects.push(p);state.project=p.id;save();render()};
    const pe=$('#v3ProjectEdit');if(pe)pe.onsubmit=e=>{e.preventDefault();const p=data.clients.find(x=>x.id===state.client).projects.find(x=>x.id===state.project),f=new FormData(pe);p.status=f.get('status');p.projectType=f.get('type');p.due=f.get('due');p.eventDate=f.get('event');p.publishDelay=Number(f.get('delay')||0);p.publishDate=f.get('publish')||(p.eventDate?dayAfter(p.eventDate,p.publishDelay):'');p.notes=f.get('notes');save();render()};
    document.querySelectorAll('[data-v3-published]').forEach(b=>b.onclick=()=>{const p=data.clients.find(x=>x.id===state.client).projects.find(x=>x.id===b.dataset.v3Published);p.published=!p.published;save();render()});
    const ck=$('#v3CheckNew');if(ck)ck.onsubmit=e=>{e.preventDefault();const p=data.clients.find(x=>x.id===state.client).projects.find(x=>x.id===state.project),f=new FormData(ck);p.checklist.push({id:id(),text:f.get('text').trim(),done:false});save();render()};
    document.querySelectorAll('[data-v3-check]').forEach(x=>x.onchange=()=>{const p=data.clients.find(c=>c.id===state.client).projects.find(p=>p.id===state.project),i=p.checklist.find(i=>i.id===x.dataset.v3Check);i.done=x.checked;save();render()});
    document.querySelectorAll('[data-v3-check-del]').forEach(b=>b.onclick=()=>{const p=data.clients.find(c=>c.id===state.client).projects.find(p=>p.id===state.project);p.checklist=p.checklist.filter(i=>i.id!==b.dataset.v3CheckDel);save();render()});
    const py=$('#v3Pay');if(py)py.onsubmit=e=>{e.preventDefault();const p=data.clients.find(x=>x.id===state.client).projects.find(x=>x.id===state.project),f=new FormData(py);p.payments.push({id:id(),amount:Number(f.get('amount')),date:f.get('date'),note:f.get('note').trim()});save();render()};
    document.querySelectorAll('[data-v3-pay-del]').forEach(b=>b.onclick=()=>{const p=data.clients.find(c=>c.id===state.client).projects.find(p=>p.id===state.project);p.payments=p.payments.filter(x=>x.id!==b.dataset.v3PayDel);save();render()});
    const as=$('#v3Assets');if(as){const input=as.elements.file,prev=as.querySelector('[data-v3-preview]'),st=as.querySelector('[data-v3-status]');input.onchange=()=>{prev.innerHTML='';[...input.files].forEach(f=>{const im=document.createElement('img');im.src=URL.createObjectURL(f);im.onload=()=>URL.revokeObjectURL(im.src);prev.appendChild(im)})};as.onsubmit=async e=>{e.preventDefault();const p=data.clients.find(x=>x.id===state.client).projects.find(x=>x.id===state.project),f=new FormData(as);st.textContent='جارٍ حفظ الصور…';try{for(const file of [...input.files]){const med=await saveImage(file,{max:1400,q:.78});p.assets.push({id:id(),...med,status:f.get('status'),caption:f.get('caption').trim()})}save();render()}catch{st.textContent='تعذّر حفظ الصور. جرّبي PNG أو JPG أو WebP.'}}}
    document.querySelectorAll('[data-v3-asset-del]').forEach(b=>b.onclick=async()=>{const p=data.clients.find(c=>c.id===state.client).projects.find(p=>p.id===state.project),a=p.assets.find(x=>x.id===b.dataset.v3AssetDel);if(a?.local)await del(a.local).catch(()=>{});p.assets=p.assets.filter(x=>x.id!==b.dataset.v3AssetDel);save();render()});

    const co=$('#v3Course');if(co)co.onsubmit=e=>{e.preventDefault();const f=new FormData(co),c={id:id(),title:f.get('title').trim(),items:[]};data.learningSpaces.push(c);state.course=c.id;save();render()};
    document.querySelectorAll('[data-v3-course]').forEach(b=>b.onclick=()=>{state.course=b.dataset.v3Course;render()});
    document.querySelector('[data-v3-course-back]')?.addEventListener('click',()=>{state.course=null;render()});
    const ci=$('#v3CourseItem');if(ci)ci.onsubmit=async e=>{e.preventDefault();const c=data.learningSpaces.find(x=>x.id===state.course),f=new FormData(ci),file=ci.elements.file.files?.[0],st=ci.querySelector('[data-v3-learning-status]');try{let media=null;if(file)media=await saveImage(file,{max:1400,q:.78});c.items.push({id:id(),title:f.get('title').trim(),type:f.get('type'),url:f.get('url'),media,note:f.get('note').trim(),watched:f.get('watched')==='on'});save();render()}catch{st.textContent='تعذّر حفظ الصورة.'}};
    document.querySelectorAll('[data-v3-course-toggle]').forEach(b=>b.onclick=()=>{const c=data.learningSpaces.find(x=>x.id===state.course),i=c.items.find(x=>x.id===b.dataset.v3CourseToggle);i.watched=!i.watched;save();render()});

    const bg=$('#v3Bg');if(bg){const input=bg.elements.file,prev=bg.querySelector('[data-v3-bg-prev]'),st=bg.querySelector('[data-v3-bg-status]');input.onchange=()=>{prev.innerHTML='';const f=input.files?.[0];if(f){const im=document.createElement('img');im.src=URL.createObjectURL(f);im.onload=()=>URL.revokeObjectURL(im.src);prev.appendChild(im)}};bg.onsubmit=async e=>{e.preventDefault();try{data.designSettings.backgroundMedia=await saveImage(input.files?.[0],{max:1800,q:.8});data.designSettings.background=null;save();st.textContent='✓ تم حفظ الخلفية';render()}catch{st.textContent='تعذّر حفظ الخلفية.'}}}
    document.querySelector('[data-v3-bg-clear]')?.addEventListener('click',async()=>{const x=data.designSettings.backgroundMedia;if(x?.local)await del(x.local).catch(()=>{});data.designSettings.backgroundMedia=null;data.designSettings.background=null;document.documentElement.style.setProperty('--yomi-user-bg','none');document.body.dataset.userBg='0';save();render()});
    const sf=$('#v3Sticker');if(sf){const input=sf.elements.file,prev=sf.querySelector('[data-v3-sticker-prev]');input.onchange=()=>{prev.innerHTML='';const f=input.files?.[0];if(f){const im=document.createElement('img');im.src=URL.createObjectURL(f);im.onload=()=>URL.revokeObjectURL(im.src);prev.appendChild(im)}};sf.onsubmit=async e=>{e.preventDefault();const f=new FormData(sf),file=input.files?.[0],text=String(f.get('text')||'').trim();if(!file&&!text)return;let med={};if(file)med=await saveImage(file,{max:700,q:.9,alpha:true});data.designSettings.stickers.push({id:id(),...med,text,target:f.get('target'),x:Number(f.get('x')),y:Number(f.get('y')),size:Number(f.get('size')),hidden:false});save();render()}}
    document.querySelectorAll('[data-v3-sticker-toggle]').forEach(b=>b.onclick=()=>{const s=data.designSettings.stickers.find(x=>x.id===b.dataset.v3StickerToggle);s.hidden=!s.hidden;save();render()});
    document.querySelectorAll('[data-v3-sticker-del]').forEach(b=>b.onclick=async()=>{const s=data.designSettings.stickers.find(x=>x.id===b.dataset.v3StickerDel);if(s?.local)await del(s.local).catch(()=>{});data.designSettings.stickers=data.designSettings.stickers.filter(x=>x.id!==b.dataset.v3StickerDel);save();render()});

    document.querySelector('[data-v3-cycle-save]')?.addEventListener('click',()=>{const n=Number($('#v3CycleLen').value);if(Number.isInteger(n)&&n>=1&&n<=14){data.cyclePeriodLength=n;save();render()}});
    document.querySelectorAll('[data-v3-period]').forEach(b=>b.onclick=()=>{const p=data.periods.find(x=>x.id===b.dataset.v3Period),s=prompt('تاريخ البداية YYYY-MM-DD',p.start);if(s===null)return;const e=prompt('تاريخ النهاية YYYY-MM-DD — اتركيه فارغًا إذا مفتوحة',p.end||'');if(e===null)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||(e&&!/^\d{4}-\d{2}-\d{2}$/.test(e))||(e&&e<s)){alert('راجعي التاريخ');return}p.start=s;p.end=e;save();render()});
    const dp=$('#v3DebtPerson');if(dp)dp.onsubmit=e=>{e.preventDefault();const f=new FormData(dp);data.debtPeople.push({id:id(),name:f.get('name').trim(),transactions:[]});save();render()};
    document.querySelectorAll('[data-v3-debt]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const p=data.debtPeople.find(x=>x.id===f.dataset.v3Debt),d=new FormData(f),a=Number(d.get('amount')),t=d.get('type'),delta={owed:a,owe:-a,received:-a,paid:a}[t],label={owed:'مبلغ مستحق لي',owe:'مبلغ مستحق عليّ',received:'استلام دفعة',paid:'دفع دفعة'}[t];p.transactions.push({id:id(),date:d.get('date'),delta,label,note:d.get('note').trim()});save();render()})
  }

  ensure();
  const w=pages.findIndex(x=>x[0]==='worship');if(w>=0)pages.splice(w,1);const h=pages.findIndex(x=>x[0]==='home');pages.splice(h+1,0,['worship','عبادتي']);
  const oldRender=render;
  render=function(){
    ensure();const custom={planner,worship,clients,learning,customize};
    if(custom[page]){nav();$('#todayLabel').textContent=dateLabel(today());$('#view').innerHTML=custom[page]();attachCommon();window.yomiTimerRender?.();window.yomiThemeApply?.();attach();stickers();paint();return}
    oldRender();
    if(page==='home'){$('#view').insertAdjacentHTML('afterbegin',homeExtra());attach()}
    if(page==='cycle'){$('#view').insertAdjacentHTML('beforeend',cycleExtra());attach()}
    if(page==='finance'){document.querySelector('.y2-debts')?.remove();$('#view').insertAdjacentHTML('beforeend',debtExtra());attach()}
    stickers();paint()
  };
  window.addEventListener('yomi-pin-unlocked',()=>{stickers();paint()});
  window.addEventListener('yomi-cloud-session',()=>{syncMedia();paint()});
  render();
})();